name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libunwind-dev
          sudo apt install -y --fix-broken build-essential git python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev libgstreamer1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good libsqlite3-dev sqlite3 bzip2 libbz2-dev libffi-dev libssl-dev

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Buildozer
        run: |
          pip install --user --upgrade buildozer Cython==0.29.33 virtualenv

      - name: Build with Buildozer
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # 1. Сначала принимаем все лицензии Android SDK вручную
          # Путь к sdkmanager внутри папки buildozer
          mkdir -p $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin
          # Эта команда автоматически говорит "y" на все запросы лицензий
          yes | $HOME/.android/repository/tools/bin/sdkmanager --licenses || true
          
          # 2. Запускаем сборку
          buildozer -v android debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
